name: BroadcastSav2Ops 
version: 1.9.2
description: Simple plugin to broadcast a message to Ops server is saving.
author: Sycholic
website: http://www.spigotmc.org/members/sycholic.40800/
main: com.sycholic.broadcastsav2ops.OpsSaveBroadcast
database: false